apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
  labels:
    app: config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
      - name: config-server-app
        image: khushi1701/config-server
        imagePullPolicy: Always
        ports:
        - containerPort: 9296
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
spec:
  selector:
    app: config-server-app
  type: ClusterIP  # Default Service Type
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9296