apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-app
  labels:
    app: gateway-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server-app
  template:
    metadata:
      labels:
        app: gateway-server-app
    spec:
      containers:
      - name: gateway-server-app
        image: khushi1701/gateway-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8765
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server-svc
spec:
  selector:
    app: gateway-server-app
  type: LoadBalancer # Common Gateway To Manage Traffice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8765