server:
  port: 9002
  
spring:
  application:
    name: user-service
  profiles:
    active:
    - localhost
  zipkin:
    base-url: http://localhost:9411/
  config:
    import: optional:configserver:bootstrap.yml
   
 