# Run Zipkin Server
# docker run -d -p 9411:9411 openzipkin/zipkin

version: '2'

services:
  zookeeper:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
      
# docker-compose -f zipkin-server.yml up