server:
  port: 9296
  
spring:
  application:
    name: config-server
  profiles:
    active:
    - localhost   
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sam-Dragon/config-server
          clone-on-start: true  